### ISSUE TITLE
Release a new Python 3 compatible version on pypi

### ISSUE THREAD

**Issue by davidbgk** [regardscitoyens/senapy#6]
Hello,

Since [that commit](https://github.com/regardscitoyens/senapy/commit/9f062cc609f6fc9ea3a0faec0f223a04b572222d), there has been no release which means that [install procedure using pip + Python 3](https://github.com/regardscitoyens/senapy#install) will fail.

The error on a fresh install via pypi is:

```
LONG_DESC = readme.read().decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

Is that possible to publish a new version on Pypi to ease the installation/reuse of that code?

Thanks!

**Comment by boogheta** [comment]
Hey @davidbgk, the current code is python 3 compatible (not python2 compatible anymore though). Although we don't have all the keys to publish a proper release :/ (ping @fmassot, I believe you're the only one that can give to @mdamien rights to the RegardsCitoyens pypi group ?)
Until a proper release is deployed, you can install the latest via "pip install -e git+https://github.com/regardscitoyens/senapy.git#egg=senapy"

**Comment by mdamien** [comment]
Thanks for the suggestion @davidbgk, a new version of senapy was released and your error should be fixed.

**Comment by davidbgk** [comment]
Woot! I confirm that it works now, thanks for your reactivity 👍
