### ISSUE TITLE
Add Transparence ordinaire to tests, and maybe also both confiance

### ISSUE THREAD

**Issue by boogheta** [regardscitoyens/senapy#7]
I would do it, but I'm not really confident on how is the good way to add a text to the tests here

**Comment by mdamien** [comment]
You would have to add a directory to `tests/resources/verified_dosleg` with an `input.html` with `<!-- URL_SENAT=http://www.senat.fr/dossier-legislatif/pjl12-689.html -->` at the end

Then, it's a matter of running `tests/tools/regen_regressions_output.py` so it adds `output.json` automatically.

If you add an empty `anpy.json` to the directory, it will also generate the comparaison with the `anpy` output.

Yup, it's a bit tricky :)

**Comment by boogheta** [comment]
Thanks !
